version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: portfolio_postgres
    restart: always
    environment:
      POSTGRES_USER: portfolio_zrpm_user
      POSTGRES_PASSWORD: rErzkDKCOFxQYwKaWtGMmsAJwPzhKcDm
      POSTGRES_DB: portfolio_zrpm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  portfolio_app:
    build: .
    container_name: portfolio_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio_zrpm?sslmode=disable
      SPRING_DATASOURCE_USERNAME: portfolio_zrpm_user
      SPRING_DATASOURCE_PASSWORD: rErzkDKCOFxQYwKaWtGMmsAJwPzhKcDm

volumes:
  postgres_data:
